### ISSUE TITLE
New gem release

### ISSUE THREAD

**Issue by radar** [spreedly/gala#23]
Hello, thank you for this wonderful gem!

Would you mind releasing a new gem version so that we can point to a RubyGems version rather than GitHub repo?

**Comment by jknipp** [comment]
Hi @radar I pushed the latest tagged version we have for the `gala` gem to RubyGems. Version `0.5.0` is now available.

**Comment by jenniferhopwood** [comment]
Thanks so much @jknipp, you've made my day!
