### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by jimdoescode** [spreedly/gala#5]
I was curious to know what this gem was licensed under? I searched through all the code and found nothing. Do you mind adding a license file so that I know how I can use this code?

**Comment by rwdaigle** [comment]
@jimdoescode @ntalbott 

I'll be honest, I'm pretty lackadaisical when it comes to understanding licenses, my only real experience working with an OSS license being [ActiveMerchant](https://github.com/activemerchant/active_merchant/blob/master/MIT-LICENSE), which uses the MIT license.

Would MIT be sufficient for your needs, @jimdoescode, and does it work for us @ntalbott?

**Comment by ntalbott** [comment]
:+1: on MIT.

**Comment by jimdoescode** [comment]
I understand it's usually the last thing I think about in my projects as well. I always use the MIT license it works great!
