### ISSUE TITLE
Distribute Gala as a Ruby gem

### ISSUE THREAD

**Issue by dankimio** [spreedly/gala#6]

**Comment by rwdaigle** [comment]
http://guides.rubygems.org/make-your-own-gem/

**Comment by rwdaigle** [comment]
Adding to @spreedly/product-dev backlog.

**Comment by dankimio** [comment]
Hi @rwdaigle! If you add me as a collaborator here and on RubyGems (itsdanya@gmail.com) I could make a release.

**Comment by rwdaigle** [comment]
Hi @dankimio - thank you for the offer!

A great first step would be a PR with the necessary files and instructions for building and releasing the gem? I believe we should then run the actual release command ourselves as the owner of the project.

**Comment by dankimio** [comment]
@rwdaigle Okay! I'll prepare the PR soon.
